### ISSUE TITLE
React Native Support????//?/???????????????

### ISSUE THREAD

**Issue by captainbarbosa** [samfader/f8r-sdk#1]
Does this library support REACT NATIVE, i try to use it but i get this error:

Printing description of connectingSceneSession:
<UISceneSession: 0x600001b69900; scene = (null); role = UIWindowSceneSessionRoleApplication; sceneConfiguration = <UISceneConfiguration: 0x600001b69880>; persistentIdentifier = 69D7E207-1618-4F76-BFBC-28BFF0584553; userInfo = <__NSDictionary0: 0x7fff806228e0>
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00000001025495f2 f8ersdk`AppDelegate.application(application=0x00007f7f57100240, connectingSceneSession=0x0000600001b69900, options=0x0000600000e39320, self=0x0000600000c0c120) at AppDelegate.swift:27:16
    frame #1: 0x0000000102549771 f8ersdk`@objc AppDelegate.application(_:configurationForConnecting:options:) at <compiler-generated>:0
    frame #2: 0x00007fff4808f0fd UIKitCore`-[UIApplication _connectUISceneFromFBSScene:transitionContext:] + 903
    frame #3: 0x00007fff4808f4b2 UIKitCore`-[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 304
    frame #4: 0x00007fff47bfa7f5 UIKitCore`-[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
    frame #5: 0x00007fff365d6165 FrontBoardServices`-[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 442
    frame #6: 0x00007fff365fc4d8 FrontBoardServices`__86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154 + 102
    frame #7: 0x00007fff365e0c45 FrontBoardServices`-[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
    frame #8: 0x00007fff365fc169 FrontBoardServices`__86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 355
    frame #9: 0x000000010286fd48 libdispatch.dylib`_dispatch_client_callout + 8
    frame #10: 0x0000000102872cb9 libdispatch.dylib`_dispatch_block_invoke_direct + 300
    frame #11: 0x00007fff3662237e FrontBoardServices`__FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
    frame #12: 0x00007fff3662206c FrontBoardServices`-[FBSSerialQueue _queue_performNextIfPossible] + 441
    frame #13: 0x00007fff3662257b FrontBoardServices`-[FBSSerialQueue _performNextFromRunLoopSource] + 22
    frame #14: 0x00007fff23bd4471 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #15: 0x00007fff23bd439c CoreFoundation`__CFRunLoopDoSource0 + 76
    frame #16: 0x00007fff23bd3bcc CoreFoundation`__CFRunLoopDoSources0 + 268
    frame #17: 0x00007fff23bce87f CoreFoundation`__CFRunLoopRun + 1263
    frame #18: 0x00007fff23bce066 CoreFoundation`CFRunLoopRunSpecific + 438
    frame #19: 0x00007fff384c0bb0 GraphicsServices`GSEventRunModal + 65
    frame #20: 0x00007fff48092d4d UIKitCore`UIApplicationMain + 1621
    frame #21: 0x0000000102549bcb f8ersdk`main at AppDelegate.swift:12:7
    frame #22: 0x00007fff5227ec25 libdyld.dylib`start + 1
Printing description of connectingSceneSession:
<UISceneSession: 0x600001b69900; scene = (null); role = UIWindowSceneSessionRoleApplication; sceneConfiguration = <UISceneConfiguration: 0x600001b69880>; persistentIdentifier = 69D7E207-1618-4F76-BFBC-28BFF0584553; userInfo = <__NSDictionary0: 0x7fff806228e0>
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00000001025495f2 f8ersdk`AppDelegate.application(application=0x00007f7f57100240, connectingSceneSession=0x0000600001b69900, options=0x0000600000e39320, self=0x0000600000c0c120) at AppDelegate.swift:27:16
    frame #1: 0x0000000102549771 f8ersdk`@objc AppDelegate.application(_:configurationForConnecting:options:) at <compiler-generated>:0
    frame #2: 0x00007fff4808f0fd UIKitCore`-[UIApplication _connectUISceneFromFBSScene:transitionContext:] + 903
    frame #3: 0x00007fff4808f4b2 UIKitCore`-[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 304
    frame #4: 0x00007fff47bfa7f5 UIKitCore`-[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
    frame #5: 0x00007fff365d6165 FrontBoardServices`-[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 442
    frame #6: 0x00007fff365fc4d8 FrontBoardServices`__86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154 + 102
    frame #7: 0x00007fff365e0c45 FrontBoardServices`-[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
    frame #8: 0x00007fff365fc169 FrontBoardServices`__86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 355
    frame #9: 0x000000010286fd48 libdispatch.dylib`_dispatch_client_callout + 8
    frame #10: 0x0000000102872cb9 libdispatch.dylib`_dispatch_block_invoke_direct + 300
    frame #11: 0x00007fff3662237e FrontBoardServices`__FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
    frame #12: 0x00007fff3662206c FrontBoardServices`-[FBSSerialQueue _queue_performNextIfPossible] + 441
    frame #13: 0x00007fff3662257b FrontBoardServices`-[FBSSerialQueue _performNextFromRunLoopSource] + 22
    frame #14: 0x00007fff23bd4471 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #15: 0x00007fff23bd439c CoreFoundation`__CFRunLoopDoSource0 + 76
    frame #16: 0x00007fff23bd3bcc CoreFoundation`__CFRunLoopDoSources0 + 268
    frame #17: 0x00007fff23bce87f CoreFoundation`__CFRunLoopRun + 1263
    frame #18: 0x00007fff23bce066 CoreFoundation`CFRunLoopRunSpecific + 438
    frame #19: 0x00007fff384c0bb0 GraphicsServices`GSEventRunModal + 65
    frame #20: 0x00007fff48092d4d UIKitCore`UIApplicationMain + 1621
    frame #21: 0x0000000102549bcb f8ersdk`main at AppDelegate.swift:12:7
    frame #22: 0x00007fff5227ec25 libdyld.dylib`start + 1
Printing description of connectingSceneSession:
<UISceneSession: 0x600001b69900; scene = (null); role = UIWindowSceneSessionRoleApplication; sceneConfiguration = <UISceneConfiguration: 0x600001b69880>; persistentIdentifier = 69D7E207-1618-4F76-BFBC-28BFF0584553; userInfo = <__NSDictionary0: 0x7fff806228e0>
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00000001025495f2 f8ersdk`AppDelegate.application(application=0x00007f7f57100240, connectingSceneSession=0x0000600001b69900, options=0x0000600000e39320, self=0x0000600000c0c120) at AppDelegate.swift:27:16
    frame #1: 0x0000000102549771 f8ersdk`@objc AppDelegate.application(_:configurationForConnecting:options:) at <compiler-generated>:0
    frame #2: 0x00007fff4808f0fd UIKitCore`-[UIApplication _connectUISceneFromFBSScene:transitionContext:] + 903
    frame #3: 0x00007fff4808f4b2 UIKitCore`-[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 304
    frame #4: 0x00007fff47bfa7f5 UIKitCore`-[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
    frame #5: 0x00007fff365d6165 FrontBoardServices`-[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 442
    frame #6: 0x00007fff365fc4d8 FrontBoardServices`__86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154 + 102
    frame #7: 0x00007fff365e0c45 FrontBoardServices`-[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
    frame #8: 0x00007fff365fc169 FrontBoardServices`__86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 355
    frame #9: 0x000000010286fd48 libdispatch.dylib`_dispatch_client_callout + 8
    frame #10: 0x0000000102872cb9 libdispatch.dylib`_dispatch_block_invoke_direct + 300
    frame #11: 0x00007fff3662237e FrontBoardServices`__FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
    frame #12: 0x00007fff3662206c FrontBoardServices`-[FBSSerialQueue _queue_performNextIfPossible] + 441
    frame #13: 0x00007fff3662257b FrontBoardServices`-[FBSSerialQueue _performNextFromRunLoopSource] + 22
    frame #14: 0x00007fff23bd4471 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #15: 0x00007fff23bd439c CoreFoundation`__CFRunLoopDoSource0 + 76
    frame #16: 0x00007fff23bd3bcc CoreFoundation`__CFRunLoopDoSources0 + 268
    frame #17: 0x00007fff23bce87f CoreFoundation`__CFRunLoopRun + 1263
    frame #18: 0x00007fff23bce066 CoreFoundation`CFRunLoopRunSpecific + 438
    frame #19: 0x00007fff384c0bb0 GraphicsServices`GSEventRunModal + 65
    frame #20: 0x00007fff48092d4d UIKitCore`UIApplicationMain + 1621
    frame #21: 0x0000000102549bcb f8ersdk`main at AppDelegate.swift:12:7
    frame #22: 0x00007fff5227ec25 libdyld.dylib`start + 1

and here is what i see 

<img width="570" alt="Screenshot 2020-03-24 11 34 20" src="https://user-images.githubusercontent.com/10850812/77463782-69d77680-6dc3-11ea-9bca-51a0ade51965.png">

**Comment by danswick** [comment]
+1

**Comment by jc-clark** [comment]
+1

**Comment by captainbarbosa** [comment]
i also see this

<img width="408" alt="Screenshot 2020-03-24 11 36 49" src="https://user-images.githubusercontent.com/10850812/77464006-c2a70f00-6dc3-11ea-884a-d5fd2a5d68b9.png">

**Comment by samfader** [comment]
sorry no hybrid

**Comment by samfader** [comment]
please only open issue if needed

**Comment by captainbarbosa** [comment]
i need it

**Comment by danswick** [comment]
give us it

**Comment by captainbarbosa** [comment]
when will this be done?????? i have a very important production app to launch in 2 days

**Comment by samfader** [comment]
Thanks for reaching out, @captainbarbosa! 

We're working really, really hard to make the F8r SDK be the best possible product for all of our developers. At this time, there is no plan to include React Native support, but we can certainly consider this for future versions of the library.

O that this too too solid flesh would melt,
Thaw, and resolve itself into a dew!
Or that the Everlasting had not fix’d
His canon ’gainst self-slaughter! O God! O God!
How weary, stale, flat, and unprofitable
Seem to me all the uses of this world!
Fie on’t! O fie! ’tis an unweeded garden,
That grows to seed; things rank and gross in nature
Possess it merely. That it should come to this!
But two months dead!—nay, not so much, not two:
So excellent a king; that was, to this,
Hyperion to a satyr; so loving to my mother,
That he might not beteem the winds of heaven
Visit her face too roughly. Heaven and earth!
Must I remember? Why, she would hang on him
As if increase of appetite had grown
By what it fed on: and yet, within a month,—
Let me not think on’t,—Frailty, thy name is woman!—
A little month; or ere those shoes were old
With which she followed my poor father’s body
Like Niobe, all tears;—why she, even she,—
O God! a beast that wants discourse of reason,
Would have mourn’d longer,—married with mine uncle,
My father’s brother; but no more like my father
Than I to Hercules: within a month;
Ere yet the salt of most unrighteous tears
Had left the flushing in her galled eyes,
She married:— O, most wicked speed, to post
With such dexterity to incestuous sheets!
It is not, nor it cannot come to good;
But break my heart,—for I must hold my tongue.
